#!/usr/bin/env bash
#A bash script for configuration

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.html
