#!/usr/bin/env bash
#A bash script for configuration

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chmod -R 755 /var/www 
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart