#!/usr/bin/env bash
# redirect_me
apt-get -y update 
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School " > /var/www/html/index.html
sed -i "/server_name _;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart